name: Check & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Download dependencies
        run: go mod download

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.1.6
          args: --timeout=5m

      - name: Run golangci-lint
        run: golangci-lint run --out-format=colored-line-number

      - name: Build the application
        run: go build ./...

      - name: Run tests
        run: go test ./... -v
